-- Insert sample quotations data to ensure permanent storage
INSERT INTO quotations (
  id,
  client_name,
  destination,
  cargo_description,
  country_of_origin,
  freight_mode,
  request_type,
  door_delivery,
  currency,
  buy_rate,
  client_quote,
  profit,
  profit_percentage,
  total_volume_kg,
  quote_sent_by,
  remarks,
  status,
  created_by,
  created_at
) VALUES 
(
  gen_random_uuid(),
  'AFRICA WORLD CARGO',
  'CAMEROON',
  'GENERAL CARGO',
  'KENYA',
  'Air Freight',
  'import',
  'YES',
  'USD',
  2.5,
  3.5,
  1.0,
  '40.0',
  1000.0,
  'N. SOLANGE',
  'Sample quotation for testing',
  'pending',
  '00000000-0000-0000-0000-000000000001',
  now()
),
(
  gen_random_uuid(),
  'TEST CLIENT LTD',
  'UGANDA',
  'ELECTRONICS',
  'CHINA',
  'Air Freight',
  'import',
  'NO',
  'USD',
  3.0,
  4.2,
  1.2,
  '40.0',
  500.0,
  'I. ARNOLD',
  'Electronics shipment',
  'pending',
  '00000000-0000-0000-0000-000000000002',
  now()
) ON CONFLICT (id) DO NOTHING;