// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfbqylnkdgeklqhjqzlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmYnF5bG5rZGdla2xxaGpxemxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0OTgxNTIsImV4cCI6MjA3MTA3NDE1Mn0.jVtjBjtTtlpxwVV31kUUrsaqXL5IqiX10a3XDZrAkag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});